export const INSURANCE_COMPANIES = [
  'No Insurance',
  'Others',
  'State Farm',
  'Progressive',
  'GEICO',
  'Allstate',
  'USAA',
  'Farmers',
  'Liberty Mutual',
  'Travelers',
  'Auto Club Enterprises / AAA',
  'American Family',
  'Erie',
  'Auto-Owners',
  'CSAA / AAA',
  'Nationwide',
  'Mercury',
  'Sentry',
  'Kemper',
  'Automobile Club MI / AAA',
  'The Hartford',
  'New Jersey Manufacturers',
  'Amica',
  'Shelter',
  'Country Financial',
  'MAPFRE',
  'Hanover',
];
